<?php

namespace Alpa\Tools\Sucker;

use Alpa\Tools\ProxyObject\Handlers\ActionsInterface;
use Alpa\Tools\ProxyObject\ProxyAbstract;

final class Proxy extends ProxyAbstract 
{
    /**
     * Proxy constructor.
     * @param $target
     * @throws \Exception
     */
    public function __construct($target)
    {
        $this->target=$target;
        $this->handlers = new SuckerProxyHandlers($target);
    }

    /**
     * Calling a proxy object to set the scope.
     * @param $scope null|string|\Closure  The scope of the object.  If a closure function is passed, then this function will be called as a sandbox.
     * @return $this
     */
    public function & __invoke(...$args)
    {
        if ($args[0] instanceof \Closure) {
            return $this->handlers->sandbox(...$args);
        }
        $scope = $args[0];
        ($this->handlers)($scope);
        return $this;

        //return parent::__invoke($arguments); // TODO: Change the autogenerated stub
    }
}